# Generated by Django 6.0 on 2026-01-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrecord',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='dailyrecord',
            old_name='point',
            new_name='points',
        ),
    ]
