# Generated by Django 6.0 on 2026-01-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_date_dailyrecord_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrecord',
            old_name='points',
            new_name='point',
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='time',
            field=models.TimeField(default='1:15'),
            preserve_default=False,
        ),
    ]
