# Generated by Django 6.0 on 2026-01-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_points_dailyrecord_point_dailyrecord_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='time',
            field=models.DurationField(),
        ),
    ]
